### ISSUE TITLE
Italy is missing today

### ISSUE THREAD

**Issue by joennlae** [atecon/covid_19_forecast#1]
Nice job :-) But I think most of europe is currently interested in italy.

**Comment by atecon** [comment]
Glad you like it ;-)
Thanks for the hint. It's fixed now. The default MLE of the ARIMA(2,1,1) suffered from an convergency failure. This is handled now: Once ARIMA(2,1,1) fails try ARIMA(1,1,0), and if this fails try ARIMA(0,1,1) which should work almost all time ;-)
