### ISSUE TITLE
Algorithm right?

### ISSUE THREAD

**Issue by ruppde** [atecon/covid_19_forecast#2]
Hi,

the curve for Iran doesn't look right, why should it suddenly slow down?

https://github.com/atecon/covid_19_forecast/blob/master/figures/forecast_arima_maxhorizon_7_iran_.png

**Comment by atecon** [comment]
Hi, I've just re-run stuff. Not sure it looks different than before. But based on recent dynamics in Iran, this is what you gt from an ARIMA(2,1,1). May I know what you would expect from this simple model?

Best

**Comment by atecon** [comment]
Ok, I close this ticket as the discussion is over.
