### ISSUE TITLE
Fix decreasing forecast intervals

### ISSUE THREAD

**Issue by ivanMSC** [atecon/covid_19_forecast#4]
Confirmed cases will go up or stay the same with 100% probability. Having a decreasing forecast lower bound makes absolutely no sense.

For example
https://github.com/atecon/covid_19_forecast/blob/master/figures/forecast_maxhorizon_7_australia_tasmania_expost.png
![image](https://user-images.githubusercontent.com/35350256/80858347-ce89ba80-8c26-11ea-9b1f-b3e7d7f3deac.png)

**Comment by atecon** [comment]
Hi, yes, you're absolutely right. This is a side-product of the way the method is applied. Interested people may rather plot interval forecasts on (daily) changes of the level series. First differences cannot be negative in this case but one still may compute (here Gaussian) forecast intervals as an approximation. Feel free to improve this forecasting toy example ;-)
